-- AlterTable
ALTER TABLE "DirectMessage" ALTER COLUMN "audioUrls" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "imageUrls" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "videoUrls" SET DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "ProjectMessage" ALTER COLUMN "audioUrls" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "imageUrls" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "videoUrls" SET DEFAULT ARRAY[]::TEXT[];
